source 'https://rubygems.org'

gem 'rails', '4.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql2'
#gem 'activerecord-mysql2-adapter'

gem 'jquery-rails'
gem 'sass'
gem 'coffee-script'

# for attr_accessible (rail 3 compatability)
gem 'protected_attributes'

gem 'thin'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
